Repository FreakPeople/freak-CStar-backend, pull requests merged in 2024-09, with the labels that each got.

#55 fix: 메세지응답양식추가 및 메세지전송시헤더검증
  src/main/kotlin/yjh/cstar/game/application/GameEngineService.kt
  src/main/kotlin/yjh/cstar/game/presentation/response/QuizInfoResponse.kt
  src/main/kotlin/yjh/cstar/websocket/presentation/StompController.kt
Labels: 🔥 Bug, 🚀 BE, ✨ Feature

#58 feat: 내정보 조회 기능 구현
  src/main/kotlin/yjh/cstar/member/application/MemberService.kt
  src/main/kotlin/yjh/cstar/member/application/port/MemberRepository.kt
  src/main/kotlin/yjh/cstar/member/infrastructure/MemberRepositoryAdapter.kt
  src/main/kotlin/yjh/cstar/member/presentation/MemberController.kt
  src/main/kotlin/yjh/cstar/member/presentation/reponse/MemberResponse.kt
  src/test/kotlin/yjh/cstar/member/application/MemberServiceTest.kt
Labels: 🚀 BE, ✨ Feature

#60 fix: 게임 종료 시 방 상태를 초기화
  src/main/kotlin/yjh/cstar/game/application/GameResultService.kt
  src/main/kotlin/yjh/cstar/room/application/RoomService.kt
  src/main/kotlin/yjh/cstar/room/domain/Room.kt
  src/test/kotlin/yjh/cstar/game/application/GameAnswerQueueServiceTest.kt
  src/test/kotlin/yjh/cstar/game/application/GameResultServiceTest.kt
  src/test/kotlin/yjh/cstar/redis/RedisTest.kt
Labels: 🔥 Bug, 🎨 Style, 💯 Test

#62 feat: 특정 카테고리에 속하는 퀴즈 목록 조회 기능 구현
  src/main/kotlin/yjh/cstar/quiz/application/QuizService.kt
  src/main/kotlin/yjh/cstar/quiz/application/port/QuizRepository.kt
  src/main/kotlin/yjh/cstar/quiz/infrastructure/QuizRepositoryAdapter.kt
  src/main/kotlin/yjh/cstar/quiz/infrastructure/jpa/QuizJpaRepository.kt
  src/main/kotlin/yjh/cstar/quiz/presentation/QuizController.kt
  src/main/kotlin/yjh/cstar/quiz/presentation/response/QuizResponse.kt
  src/test/kotlin/yjh/cstar/quiz/application/QuizServiceTest.kt
Labels: 🚀 BE, ✨ Feature, 💯 Test

#64 feat: 웹소켓 연결 종료시 게임방 인원 감소 기능 구현
  src/main/kotlin/yjh/cstar/auth/jwt/TokenProvider.kt
  src/main/kotlin/yjh/cstar/common/BaseErrorCode.kt
  src/main/kotlin/yjh/cstar/room/application/RoomService.kt
  src/main/kotlin/yjh/cstar/room/domain/Room.kt
  src/main/kotlin/yjh/cstar/websocket/presentation/StompWebSocketEventHandler.kt
  src/test/kotlin/yjh/cstar/room/domain/RoomTest.kt
Labels: 🚀 BE, ✨ Feature

#67 refactor : 퀴즈게임 진행중 실시간 랭킹 정보를 전송하도록 개선
  src/main/kotlin/yjh/cstar/game/application/GameEngineService.kt
  src/main/kotlin/yjh/cstar/game/domain/AnswerResult.kt
  src/main/kotlin/yjh/cstar/game/infrastructure/redis/AnswerResultEntity.kt
  src/main/kotlin/yjh/cstar/game/presentation/response/RankingResponse.kt
  src/main/kotlin/yjh/cstar/websocket/presentation/StompController.kt
  src/main/kotlin/yjh/cstar/websocket/presentation/request/AnswerMessageRequest.kt
  src/test/kotlin/yjh/cstar/game/application/GameAnswerQueueServiceTest.kt
  src/test/kotlin/yjh/cstar/redis/RedisTest.kt
Labels: 🚀 BE, 🛠 Refactor

#69 refactor: CORS 허용 주소 변경
  src/main/kotlin/yjh/cstar/config/WebConfig.kt
  src/main/resources/application-local.yml
  src/test/resources/application-local-test.yml
Labels: 🛠 Refactor

#71 refactor: ThreadPool 사이즈 변경
  src/main/kotlin/yjh/cstar/config/AsyncConfig.kt
  src/main/resources/application-local.yml
  src/test/resources/application-local-test.yml
Labels: 🚀 BE, 🛠 Refactor

#73 feat: 카테고리별 퀴즈 생성 및 데이터베이스 삽입
  src/main/kotlin/yjh/cstar/game/application/GameEngineService.kt
  src/main/resources/application-local.yml
  src/main/resources/data/init_insert_quiz_data.sql
Labels: 🚀 BE, ✨ Feature

#75 refactor: 도커 파일 구조화
  .gitignore
  docker-compose.yml
  docker/app/Dockerfile
  docker/docker-compose.yml
Labels: 🚀 BE, ✨ Feature, 🛠 Refactor

#83 refactor: 게임 엔진 서비스의 Busy Waiting 문제 개선
  src/main/kotlin/yjh/cstar/game/infrastructure/QueueRepositoryAdapter.kt
  src/main/kotlin/yjh/cstar/game/infrastructure/redis/RedisQueueRepository.kt
  src/test/kotlin/yjh/cstar/redis/RedisConcurrencyTest.kt
  src/test/kotlin/yjh/cstar/redis/RedisTest.kt
Labels: 🚀 BE, 🛠 Refactor

#84 fix: flyway 적용
  build.gradle.kts
  src/main/resources/application-local.yml
  src/main/resources/db/V1__init.sql
  src/main/resources/db/V2__alter_member_table_for_unique.sql
  src/main/resources/db/init_schema.sql
  src/main/resources/db/v2_alter_member_table_for_unique.sql
  src/test/resources/application-local-test.yml
Labels: 🔥 Bug, 🚀 BE, ✨ Feature

#85 refactor: game패키지구조분리
  src/main/kotlin/yjh/cstar/engine/application/GameAnswerPollService.kt
  src/main/kotlin/yjh/cstar/engine/application/GameEngineService.kt
  src/main/kotlin/yjh/cstar/engine/application/port/GameAnswerPollRepository.kt
  src/main/kotlin/yjh/cstar/engine/infrastructure/GameAnswerPollRepositoryAdapter.kt
  src/main/kotlin/yjh/cstar/engine/infrastructure/redis/AnswerResultEntity.kt
  src/main/kotlin/yjh/cstar/game/application/GameAnswerQueueService.kt
  src/main/kotlin/yjh/cstar/game/application/port/QueueService.kt
  src/main/kotlin/yjh/cstar/game/infrastructure/QueueRepositoryAdapter.kt
  src/main/kotlin/yjh/cstar/util/RedisUtil.kt
  src/main/kotlin/yjh/cstar/websocket/application/BroadCastService.kt
  src/main/kotlin/yjh/cstar/websocket/application/GameAnswerPushService.kt
  src/main/kotlin/yjh/cstar/websocket/application/port/GameAnswerPushRepository.kt
  src/main/kotlin/yjh/cstar/websocket/infrastructure/GameAnswerPushRepositoryAdapter.kt
  src/main/kotlin/yjh/cstar/websocket/presentation/StompController.kt
  src/test/kotlin/yjh/cstar/engine/application/GameAnswerPollServiceTest.kt
  src/test/kotlin/yjh/cstar/redis/RedisConcurrencyTest.kt
  src/test/kotlin/yjh/cstar/redis/RedisTest.kt
  src/test/kotlin/yjh/cstar/websocket/application/GameAnswerPushServiceTest.kt
Labels: 🚀 BE, 🛠 Refactor

#87 feat: 카테고리 테이블 생성 및 퀴즈,게임 테이블 수정
  src/main/kotlin/yjh/cstar/category/domain/Category.kt
  src/main/kotlin/yjh/cstar/category/domain/CategoryType.kt
  src/main/kotlin/yjh/cstar/category/infrastructure/jpa/CategoryEntity.kt
  src/main/kotlin/yjh/cstar/category/infrastructure/jpa/CategoryJpaRepository.kt
  src/main/kotlin/yjh/cstar/common/BaseErrorCode.kt
  src/main/kotlin/yjh/cstar/engine/application/GameEngineService.kt
  src/main/kotlin/yjh/cstar/game/application/GameResultService.kt
  src/main/kotlin/yjh/cstar/game/application/GameService.kt
  src/main/kotlin/yjh/cstar/game/domain/Game.kt
  src/main/kotlin/yjh/cstar/game/domain/GameStartCommand.kt
  src/main/kotlin/yjh/cstar/game/infrastructure/jpa/GameEntity.kt
  src/main/kotlin/yjh/cstar/game/presentation/request/GameStartRequest.kt
  src/main/kotlin/yjh/cstar/quiz/application/QuizService.kt
  src/main/kotlin/yjh/cstar/quiz/application/port/QuizRepository.kt
  src/main/kotlin/yjh/cstar/quiz/domain/Quiz.kt
  src/main/kotlin/yjh/cstar/quiz/domain/QuizCreateCommand.kt
  src/main/kotlin/yjh/cstar/quiz/infrastructure/QuizRepositoryAdapter.kt
  src/main/kotlin/yjh/cstar/quiz/infrastructure/jpa/QuizEntity.kt
  src/main/kotlin/yjh/cstar/quiz/infrastructure/jpa/QuizJpaRepository.kt
  src/main/kotlin/yjh/cstar/quiz/presentation/QuizController.kt
  src/main/kotlin/yjh/cstar/quiz/presentation/request/QuizCreateRequest.kt
  src/main/kotlin/yjh/cstar/quiz/presentation/response/QuizResponse.kt
  src/main/resources/data/init_insert_category_data.sql
  src/main/resources/data/init_insert_quiz_data.sql
  src/main/resources/db/V1__init.sql
  src/main/resources/db/V3__create_category_table_and_alter_quiz_game_tables.sql
  src/test/kotlin/yjh/cstar/game/application/GameResultServiceTest.kt
  src/test/kotlin/yjh/cstar/jpa/JpaTest.kt
  src/test/kotlin/yjh/cstar/quiz/application/QuizServiceTest.kt
  src/test/kotlin/yjh/cstar/quiz/domain/QuizTest.kt
Labels: 🚀 BE, ✨ Feature, 🛠 Refactor, 💯 Test

#91 fix: sql.init을 사용하지 않도록 제거
  src/main/resources/application-local.yml
Labels: 🔥 Bug, 🚀 BE

#88 refactor: GameEngineService의 책임을 분리하여 구조 개선
  src/main/kotlin/yjh/cstar/engine/application/AnswerValidationService.kt
  src/main/kotlin/yjh/cstar/engine/application/GameEngineService.kt
  src/main/kotlin/yjh/cstar/engine/application/RankingService.kt
  src/main/kotlin/yjh/cstar/engine/application/ScoreManagementService.kt
  src/main/kotlin/yjh/cstar/engine/domain/Ranking.kt
  src/main/kotlin/yjh/cstar/game/application/GameResultService.kt
  src/main/kotlin/yjh/cstar/game/application/GameService.kt
  src/main/kotlin/yjh/cstar/game/presentation/request/RankingCreateRequest.kt
  src/test/kotlin/yjh/cstar/engine/application/AnswerValidationServiceTest.kt
  src/test/kotlin/yjh/cstar/engine/application/RankingServiceTest.kt
  src/test/kotlin/yjh/cstar/engine/application/ScoreManagementServiceTest.kt
  src/test/kotlin/yjh/cstar/game/application/GameResultServiceTest.kt
Labels: 🚀 BE, 🛠 Refactor, 💯 Test

#92 refactor: 실시간게임랭킹산정기능을sorted set을활용하도록개선
  src/main/kotlin/yjh/cstar/engine/application/GameEngineService.kt
  src/main/kotlin/yjh/cstar/engine/application/RankingService.kt
  src/main/kotlin/yjh/cstar/engine/application/RedisRankingService.kt
  src/main/kotlin/yjh/cstar/game/application/GameResultService.kt
  src/main/kotlin/yjh/cstar/game/presentation/request/RankingCreateRequest.kt
  src/main/kotlin/yjh/cstar/util/RedisUtil.kt
  src/test/kotlin/yjh/cstar/engine/application/RankingServiceTest.kt
  src/test/kotlin/yjh/cstar/engine/application/RedisRankingServiceTest.kt
  src/test/kotlin/yjh/cstar/game/application/GameResultServiceTest.kt
  src/test/resources/application-local-test.yml
  src/test/resources/testdb/schema.sql
Labels: 🚀 BE, 🛠 Refactor

#93 refactor: redis List자료구조에 ttl 설정하기
  src/main/kotlin/yjh/cstar/engine/application/GameEngineService.kt
  src/main/kotlin/yjh/cstar/util/RedisUtil.kt
  src/main/kotlin/yjh/cstar/websocket/infrastructure/GameAnswerPushRepositoryAdapter.kt
Labels: 🚀 BE, 🛠 Refactor

#96 refactor: Dockerfile 경로 변경에 따른 deploy.yml 수정
  .github/workflows/deploy.yml
Labels: 🚀 BE, 🛠 Refactor

#97 docs: README 프로젝트 정리
  README.md
Labels: 🚀 BE, 📚 Docs

#99 refactor: 배포 브랜치 변경
  .github/workflows/deploy.yml
Labels: 🚀 BE, 🛠 Refactor

#101 refactor: game engine service 리팩토링
  src/main/kotlin/yjh/cstar/engine/application/GameEngineService.kt
  src/main/kotlin/yjh/cstar/engine/application/RankingService.kt
  src/main/kotlin/yjh/cstar/engine/application/RedisRankingService.kt
  src/main/kotlin/yjh/cstar/engine/domain/GameManager.kt
  src/main/kotlin/yjh/cstar/engine/domain/Player.kt
  src/main/kotlin/yjh/cstar/engine/domain/Players.kt
  src/main/kotlin/yjh/cstar/engine/domain/Quizzes.kt
  src/main/kotlin/yjh/cstar/engine/domain/StartTime.kt
  src/test/kotlin/yjh/cstar/engine/application/RankingServiceTest.kt
  src/test/kotlin/yjh/cstar/engine/application/RedisRankingServiceTest.kt
Labels: 🚀 BE, 🛠 Refactor

#103 refactor: engine도메인 리팩토링하기
  src/main/kotlin/yjh/cstar/engine/application/AnswerValidationService.kt
  src/main/kotlin/yjh/cstar/engine/application/GameAnswerPollService.kt
  src/main/kotlin/yjh/cstar/engine/application/GameEngineService.kt
  src/main/kotlin/yjh/cstar/engine/application/QuizGameService.kt
  src/main/kotlin/yjh/cstar/engine/application/RankingService.kt
  src/main/kotlin/yjh/cstar/engine/application/ScoreManagementService.kt
  src/main/kotlin/yjh/cstar/engine/domain/GameManager.kt
  src/main/kotlin/yjh/cstar/engine/domain/Player.kt
  src/main/kotlin/yjh/cstar/engine/domain/Players.kt
  src/main/kotlin/yjh/cstar/engine/domain/Quizzes.kt
  src/main/kotlin/yjh/cstar/engine/domain/Ranking.kt
  src/main/kotlin/yjh/cstar/engine/domain/StartTime.kt
  src/main/kotlin/yjh/cstar/engine/domain/game/GameInfo.kt
  src/main/kotlin/yjh/cstar/engine/domain/game/GameInitializable.kt
  src/main/kotlin/yjh/cstar/engine/domain/game/GameRunnable.kt
  src/main/kotlin/yjh/cstar/engine/domain/game/QuizGame.kt
  src/main/kotlin/yjh/cstar/engine/domain/io/ExternalInputHandler.kt
  src/main/kotlin/yjh/cstar/engine/domain/io/ExternalOutputHandler.kt
  src/main/kotlin/yjh/cstar/engine/domain/io/ExternalRankingHandler.kt
  src/main/kotlin/yjh/cstar/engine/domain/io/InputHandler.kt
  src/main/kotlin/yjh/cstar/engine/domain/io/OutputHandler.kt
  src/main/kotlin/yjh/cstar/engine/domain/io/RankingHandler.kt
  src/main/kotlin/yjh/cstar/engine/domain/player/Players.kt
  src/main/kotlin/yjh/cstar/engine/domain/quiz/PlayerAnswer.kt
  src/main/kotlin/yjh/cstar/engine/domain/quiz/Quiz.kt
  src/main/kotlin/yjh/cstar/engine/domain/ranking/Ranking.kt
  src/main/kotlin/yjh/cstar/game/application/GameResultService.kt
  src/main/kotlin/yjh/cstar/game/application/GameService.kt
  src/main/kotlin/yjh/cstar/game/domain/AnswerResult.kt
  src/main/kotlin/yjh/cstar/game/presentation/request/RankingCreateRequest.kt
  src/main/kotlin/yjh/cstar/member/application/MemberService.kt
  src/main/kotlin/yjh/cstar/member/application/port/MemberRepository.kt
  src/main/kotlin/yjh/cstar/member/infrastructure/MemberRepositoryAdapter.kt
  src/test/kotlin/yjh/cstar/engine/application/AnswerValidationServiceTest.kt
  src/test/kotlin/yjh/cstar/engine/application/GameAnswerPollServiceTest.kt
  src/test/kotlin/yjh/cstar/engine/application/RankingServiceTest.kt
  src/test/kotlin/yjh/cstar/engine/application/RedisRankingServiceTest.kt
  src/test/kotlin/yjh/cstar/engine/application/ScoreManagementServiceTest.kt
  src/test/kotlin/yjh/cstar/game/application/GameResultServiceTest.kt
  src/test/kotlin/yjh/cstar/redis/RedisConcurrencyTest.kt
Labels: 🚀 BE, 🛠 Refactor

#105 refactor: 퀴즈게임 도메인로직의 input output 추상화 하기
  src/main/kotlin/yjh/cstar/engine/application/GameEngineService.kt
  src/main/kotlin/yjh/cstar/engine/application/QuizGameService.kt
  src/main/kotlin/yjh/cstar/engine/application/port/AnswerProvider.kt
  src/main/kotlin/yjh/cstar/engine/application/port/GameAnswerPollRepository.kt
  src/main/kotlin/yjh/cstar/engine/application/port/GameNotifier.kt
  src/main/kotlin/yjh/cstar/engine/application/port/RankingHandler.kt
  src/main/kotlin/yjh/cstar/engine/domain/game/GameInfo.kt
  src/main/kotlin/yjh/cstar/engine/domain/game/QuizGame.kt
  src/main/kotlin/yjh/cstar/engine/domain/io/ExternalInputHandler.kt
  src/main/kotlin/yjh/cstar/engine/domain/io/InputHandler.kt
  src/main/kotlin/yjh/cstar/engine/domain/io/OutputHandler.kt
  src/main/kotlin/yjh/cstar/engine/domain/quiz/PlayerAnswer.kt
  src/main/kotlin/yjh/cstar/engine/domain/quiz/Quiz.kt
  src/main/kotlin/yjh/cstar/engine/domain/quiz/QuizDto.kt
  src/main/kotlin/yjh/cstar/engine/domain/quiz/Quizzes.kt
  src/main/kotlin/yjh/cstar/engine/infrastructure/GameAnswerPollRepositoryAdapter.kt
  src/main/kotlin/yjh/cstar/engine/infrastructure/RedisQueueAnswerProvider.kt
  src/main/kotlin/yjh/cstar/engine/infrastructure/RedisRankingHandler.kt
  src/main/kotlin/yjh/cstar/engine/infrastructure/WebsocketGameNotifier.kt
  src/main/kotlin/yjh/cstar/engine/infrastructure/redis/AnswerResultEntity.kt
  src/test/kotlin/yjh/cstar/redis/RedisConcurrencyTest.kt
Labels: 🚀 BE, 🛠 Refactor

#106 test: 퀴즈 게임 도메인 단위테스트추가
  src/main/kotlin/yjh/cstar/engine/domain/player/Players.kt
  src/main/kotlin/yjh/cstar/engine/domain/quiz/PlayerAnswer.kt
  src/main/kotlin/yjh/cstar/engine/domain/quiz/Quiz.kt
  src/main/kotlin/yjh/cstar/engine/domain/quiz/Quizzes.kt
  src/main/kotlin/yjh/cstar/engine/domain/ranking/Ranking.kt
  src/test/kotlin/yjh/cstar/engine/domain/player/PlayersTest.kt
  src/test/kotlin/yjh/cstar/engine/domain/quiz/PlayerAnswerTest.kt
  src/test/kotlin/yjh/cstar/engine/domain/quiz/QuizTest.kt
  src/test/kotlin/yjh/cstar/engine/domain/quiz/QuizzesTest.kt
  src/test/kotlin/yjh/cstar/engine/domain/ranking/RankingTest.kt
Labels: 🚀 BE, 🛠 Refactor, 💯 Test

#112 fix: jwt토큰 없어도 에러를 반환하지 않도록 수정
  src/main/kotlin/yjh/cstar/auth/jwt/JwtFilter.kt
Labels: 🔥 Bug, 🚀 BE

#115 chore: 기존 퀴즈 데이터의 잘못된 카테고리 타입 변경
  src/main/resources/data/init_insert_quiz_data.sql
Labels: 🚀 BE

#117 chore: 날짜 데이터를 동적으로 넣는 게 아닌 정적 데이터로 삽입
  src/main/resources/data/init_insert_quiz_data.sql
Labels: 🚀 BE

#118 chore: 배포 상태에서 컨테이너 삭제시 관련 이미지 삭제하도록 코드 추가
  .github/workflows/deploy.yml
Labels: 🚀 BE, 🛠 Refactor

#120 fix: GameEngineThreadPool을 GamePlayThreadPool로 이름 변경
  README.md
  src/main/kotlin/yjh/cstar/common/BaseErrorCode.kt
  src/main/kotlin/yjh/cstar/play/application/GamePlayService.kt
Labels: 🔥 Bug, 🚀 BE, 📚 Docs
