Repository FreakPeople/freak-CStar-backend, pull requests merged in 2024-08, with the labels that each got.

#10 feat: 테이블에 매칭되는 jpa 엔티티 구현
  build.gradle.kts
  src/main/kotlin/yjh/cstar/config/JpaConfig.kt
  src/main/kotlin/yjh/cstar/game/infrastructure/jpa/GameEntity.kt
  src/main/kotlin/yjh/cstar/game/infrastructure/jpa/GameJpaRepository.kt
  src/main/kotlin/yjh/cstar/game/infrastructure/jpa/GameResultEntity.kt
  src/main/kotlin/yjh/cstar/game/infrastructure/jpa/GameResultJpaRepository.kt
  src/main/kotlin/yjh/cstar/member/infrastructure/jpa/MemberEntity.kt
  src/main/kotlin/yjh/cstar/member/infrastructure/jpa/MemberJpaRepository.kt
  src/main/kotlin/yjh/cstar/quiz/domain/Category.kt
  src/main/kotlin/yjh/cstar/quiz/infrastructure/jpa/GameQuizEntity.kt
  src/main/kotlin/yjh/cstar/quiz/infrastructure/jpa/GameQuizJpaRepository.kt
  src/main/kotlin/yjh/cstar/quiz/infrastructure/jpa/QuizEntity.kt
  src/main/kotlin/yjh/cstar/quiz/infrastructure/jpa/QuizJpaRepository.kt
  src/main/kotlin/yjh/cstar/room/domain/RoomStatus.kt
  src/main/kotlin/yjh/cstar/room/infrastructure/jpa/RoomEntity.kt
  src/main/kotlin/yjh/cstar/room/infrastructure/jpa/RoomJoinEntity.kt
  src/main/kotlin/yjh/cstar/room/infrastructure/jpa/RoomJoinJpaRepository.kt
  src/main/kotlin/yjh/cstar/room/infrastructure/jpa/RoomJpaRepository.kt
  src/test/kotlin/yjh/cstar/IntegrationTest.kt
  src/test/kotlin/yjh/cstar/jpa/JpaTest.kt
  src/test/resources/application-local-test.yml
Labels: 🚀 BE, ✨ Feature

#16 feat: 방생성 기능구현
  build.gradle.kts
  src/main/kotlin/yjh/cstar/common/BaseErrorCode.kt
  src/main/kotlin/yjh/cstar/common/BaseException.kt
  src/main/kotlin/yjh/cstar/common/BaseResponse.kt
  src/main/kotlin/yjh/cstar/common/GlobalControllerAdvice.kt
  src/main/kotlin/yjh/cstar/room/application/RoomService.kt
  src/main/kotlin/yjh/cstar/room/application/port/RoomRepository.kt
  src/main/kotlin/yjh/cstar/room/domain/Room.kt
  src/main/kotlin/yjh/cstar/room/domain/RoomCreateCommand.kt
  src/main/kotlin/yjh/cstar/room/domain/RoomStatus.kt
  src/main/kotlin/yjh/cstar/room/domain/Validator.kt
  src/main/kotlin/yjh/cstar/room/infrastructure/RoomRepositoryAdapter.kt
  src/main/kotlin/yjh/cstar/room/infrastructure/jpa/RoomEntity.kt
  src/main/kotlin/yjh/cstar/room/presentation/RoomController.kt
  src/main/kotlin/yjh/cstar/room/presentation/request/RoomCreateRequest.kt
  src/test/kotlin/yjh/cstar/CstarApplicationTests.kt
  src/test/kotlin/yjh/cstar/jpa/JpaTest.kt
  src/test/kotlin/yjh/cstar/room/application/RoomServiceTest.kt
  src/test/kotlin/yjh/cstar/room/domain/RoomCreateCommandTest.kt
  src/test/kotlin/yjh/cstar/room/domain/RoomTest.kt
Labels: 🚀 BE, ✨ Feature

#17 feat: 회원 가입 기능 구현
  build.gradle.kts
  src/main/kotlin/yjh/cstar/common/BaseErrorCode.kt
  src/main/kotlin/yjh/cstar/config/SecurityConfig.kt
  src/main/kotlin/yjh/cstar/member/application/MemberService.kt
  src/main/kotlin/yjh/cstar/member/application/port/MemberRepository.kt
  src/main/kotlin/yjh/cstar/member/application/port/PasswordEncryptor.kt
  src/main/kotlin/yjh/cstar/member/domain/Member.kt
  src/main/kotlin/yjh/cstar/member/domain/MemberCreateCommand.kt
  src/main/kotlin/yjh/cstar/member/domain/Validator.kt
  src/main/kotlin/yjh/cstar/member/infrastructure/MemberRepositoryAdapter.kt
  src/main/kotlin/yjh/cstar/member/infrastructure/PasswordEncryptorAdapter.kt
  src/main/kotlin/yjh/cstar/member/infrastructure/jpa/MemberEntity.kt
  src/main/kotlin/yjh/cstar/member/infrastructure/jpa/MemberJpaRepository.kt
  src/main/kotlin/yjh/cstar/member/presentation/MemberController.kt
  src/main/kotlin/yjh/cstar/member/presentation/request/MemberCreateRequest.kt
  src/test/kotlin/yjh/cstar/member/application/MemberServiceTest.kt
  src/test/kotlin/yjh/cstar/member/domain/MemberCreateCommandTest.kt
  src/test/kotlin/yjh/cstar/member/domain/MemberTest.kt
Labels: 🚀 BE, ✨ Feature

#19 fix: 테스트 자동화 스크립트 수정
  .github/workflows/deploy.yml
  .github/workflows/test.yml
Labels: 🔥 Bug, 🚀 BE

#21 fix: url 수정 및 v1버전 표시
  src/main/kotlin/yjh/cstar/room/presentation/RoomController.kt
Labels: 🔥 Bug, 🚀 BE

#23 fix: Member 테이블의 email, nickname 에 unique 제약 조건 추가
  src/main/resources/db/v2_alter_member_table_for_unique.sql
  src/test/kotlin/yjh/cstar/member/concurrency/MemberConcurrencyTest.kt
  src/test/resources/application-local-test.yml
Labels: 🔥 Bug, 🚀 BE

#25 fix: local 개발 환경에 DB 변경사항 추가
  src/main/resources/application-local.yml
Labels: 🔥 Bug, 🚀 BE

#26 feat: 게임방 조회 기능 구현
  src/main/kotlin/yjh/cstar/room/application/RoomService.kt
  src/main/kotlin/yjh/cstar/room/application/port/RoomRepository.kt
  src/main/kotlin/yjh/cstar/room/infrastructure/RoomRepositoryAdapter.kt
  src/main/kotlin/yjh/cstar/room/infrastructure/jpa/RoomEntity.kt
  src/main/kotlin/yjh/cstar/room/infrastructure/jpa/RoomJpaRepository.kt
  src/main/kotlin/yjh/cstar/room/presentation/RoomController.kt
  src/main/kotlin/yjh/cstar/room/presentation/response/RoomResponse.kt
  src/test/kotlin/yjh/cstar/jpa/JpaTest.kt
Labels: 🔥 Bug, 🚀 BE, ✨ Feature

#29 feat: 방 참가 기능 구현
  src/main/kotlin/yjh/cstar/common/BaseErrorCode.kt
  src/main/kotlin/yjh/cstar/room/application/RoomService.kt
  src/main/kotlin/yjh/cstar/room/domain/Room.kt
  src/main/kotlin/yjh/cstar/room/presentation/RoomController.kt
  src/main/kotlin/yjh/cstar/room/presentation/request/RoomJoinRequest.kt
  src/test/kotlin/yjh/cstar/room/application/RoomServiceTest.kt
  src/test/kotlin/yjh/cstar/room/concurrency/RoomConcurrencyTest.kt
  src/test/kotlin/yjh/cstar/room/domain/RoomTest.kt
Labels: 🚀 BE, ✨ Feature

#31 feat: 로그인기능구현
  build.gradle.kts
  src/main/kotlin/yjh/cstar/auth/application/UserDetailService.kt
  src/main/kotlin/yjh/cstar/auth/jwt/JwtAccessDeniedHandler.kt
  src/main/kotlin/yjh/cstar/auth/jwt/JwtAuthenticationEntryPoint.kt
  src/main/kotlin/yjh/cstar/auth/jwt/JwtFilter.kt
  src/main/kotlin/yjh/cstar/auth/jwt/JwtSecurityConfig.kt
  src/main/kotlin/yjh/cstar/auth/jwt/TokenProvider.kt
  src/main/kotlin/yjh/cstar/auth/presentation/AuthController.kt
  src/main/kotlin/yjh/cstar/auth/presentation/request/LoginRequest.kt
  src/main/kotlin/yjh/cstar/auth/presentation/response/JwtTokenResponse.kt
  src/main/kotlin/yjh/cstar/common/BaseErrorCode.kt
  src/main/kotlin/yjh/cstar/config/SecurityConfig.kt
  src/main/kotlin/yjh/cstar/member/application/MemberService.kt
  src/main/kotlin/yjh/cstar/member/application/port/MemberRepository.kt
  src/main/kotlin/yjh/cstar/member/infrastructure/MemberRepositoryAdapter.kt
  src/main/kotlin/yjh/cstar/member/infrastructure/jpa/MemberJpaRepository.kt
  src/main/kotlin/yjh/cstar/quiz/infrastructure/jpa/GameQuizEntity.kt
  src/main/resources/application-local.yml
  src/test/kotlin/yjh/cstar/member/application/MemberServiceTest.kt
  src/test/resources/application-local-test.yml
Labels: 🚀 BE, ✨ Feature

#32 feat: 게임 방 웹소켓 연결 기능 구현
  build.gradle.kts
  src/main/kotlin/yjh/cstar/CstarApplication.kt
  src/main/kotlin/yjh/cstar/config/StompWebSocketConfig.kt
  src/main/kotlin/yjh/cstar/websocket/presentation/StompController.kt
  src/main/kotlin/yjh/cstar/websocket/presentation/StompWebSocketEventHandler.kt
  src/test/kotlin/yjh/cstar/websocket/WebSocketTest.kt
Labels: 🚀 BE, ✨ Feature

#35 feat: 게임 기능 구현
  build.gradle.kts
  docker-compose.yml
  src/main/kotlin/yjh/cstar/CstarApplication.kt
  src/main/kotlin/yjh/cstar/auth/jwt/TokenProvider.kt
  src/main/kotlin/yjh/cstar/auth/presentation/AuthController.kt
  src/main/kotlin/yjh/cstar/common/BaseErrorCode.kt
  src/main/kotlin/yjh/cstar/config/AsyncConfig.kt
  src/main/kotlin/yjh/cstar/config/RedisConfig.kt
  src/main/kotlin/yjh/cstar/config/WebConfig.kt
  src/main/kotlin/yjh/cstar/game/application/GameAnswerQueueService.kt
  src/main/kotlin/yjh/cstar/game/application/GameEngineService.kt
  src/main/kotlin/yjh/cstar/game/application/GameResultService.kt
  src/main/kotlin/yjh/cstar/game/application/GameService.kt
  src/main/kotlin/yjh/cstar/game/application/port/GameRepository.kt
  src/main/kotlin/yjh/cstar/game/application/port/GameResultRepository.kt
  src/main/kotlin/yjh/cstar/game/application/port/QueueService.kt
  src/main/kotlin/yjh/cstar/game/domain/AnswerResult.kt
  src/main/kotlin/yjh/cstar/game/domain/Game.kt
  src/main/kotlin/yjh/cstar/game/domain/GameResult.kt
  src/main/kotlin/yjh/cstar/game/domain/GameStartCommand.kt
  src/main/kotlin/yjh/cstar/game/infrastructure/GameRepositoryAdapter.kt
  src/main/kotlin/yjh/cstar/game/infrastructure/GameResultRepository.kt
  src/main/kotlin/yjh/cstar/game/infrastructure/QueueRepositoryAdapter.kt
  src/main/kotlin/yjh/cstar/game/infrastructure/jpa/GameEntity.kt
  src/main/kotlin/yjh/cstar/game/infrastructure/jpa/GameResultEntity.kt
  src/main/kotlin/yjh/cstar/game/infrastructure/redis/AnswerResultEntity.kt
  src/main/kotlin/yjh/cstar/game/infrastructure/redis/RedisQueueRepository.kt
  src/main/kotlin/yjh/cstar/game/presentation/GameController.kt
  src/main/kotlin/yjh/cstar/game/presentation/request/GameStartRequest.kt
  src/main/kotlin/yjh/cstar/quiz/application/QuizService.kt
  src/main/kotlin/yjh/cstar/quiz/application/port/QuizRepository.kt
  src/main/kotlin/yjh/cstar/quiz/domain/Category.kt
  src/main/kotlin/yjh/cstar/quiz/domain/Quiz.kt
  src/main/kotlin/yjh/cstar/quiz/infrastructure/QuizRepositoryAdapter.kt
  src/main/kotlin/yjh/cstar/quiz/infrastructure/jpa/QuizEntity.kt
  src/main/kotlin/yjh/cstar/quiz/infrastructure/jpa/QuizJpaRepository.kt
  src/main/kotlin/yjh/cstar/room/application/RoomService.kt
  src/main/kotlin/yjh/cstar/room/application/port/RoomJoinRepository.kt
  src/main/kotlin/yjh/cstar/room/domain/Room.kt
  src/main/kotlin/yjh/cstar/room/domain/RoomJoin.kt
  src/main/kotlin/yjh/cstar/room/infrastructure/RoomJoinRepositoryAdapter.kt
  src/main/kotlin/yjh/cstar/room/infrastructure/RoomRepositoryAdapter.kt
  src/main/kotlin/yjh/cstar/room/infrastructure/jpa/RoomJoinEntity.kt
  src/main/kotlin/yjh/cstar/room/infrastructure/jpa/RoomJoinJpaRepository.kt
  src/main/kotlin/yjh/cstar/websocket/presentation/StompController.kt
  src/main/kotlin/yjh/cstar/websocket/presentation/request/AnswerMessageRequest.kt
  src/main/resources/application-local.yml
  src/test/kotlin/yjh/cstar/game/application/GameAnswerQueueServiceTest.kt
  src/test/kotlin/yjh/cstar/game/application/GameResultServiceTest.kt
  src/test/kotlin/yjh/cstar/quiz/application/QuizServiceTest.kt
  src/test/kotlin/yjh/cstar/redis/RedisTest.kt
  src/test/kotlin/yjh/cstar/room/application/RoomServiceTest.kt
  src/test/resources/application-local-test.yml
Labels: 🔥 Bug, 🚀 BE, ✨ Feature, 🛠 Refactor, 🎨 Style, 💯 Test

#36 feat: 퀴즈생성기능구현
  src/main/kotlin/yjh/cstar/quiz/application/QuizService.kt
  src/main/kotlin/yjh/cstar/quiz/application/port/QuizRepository.kt
  src/main/kotlin/yjh/cstar/quiz/domain/Quiz.kt
  src/main/kotlin/yjh/cstar/quiz/domain/QuizCreateCommand.kt
  src/main/kotlin/yjh/cstar/quiz/infrastructure/QuizRepositoryAdapter.kt
  src/main/kotlin/yjh/cstar/quiz/infrastructure/jpa/QuizEntity.kt
  src/main/kotlin/yjh/cstar/quiz/presentation/QuizController.kt
  src/main/kotlin/yjh/cstar/quiz/presentation/request/QuizCreateRequest.kt
  src/test/kotlin/yjh/cstar/quiz/application/QuizServiceTest.kt
  src/test/kotlin/yjh/cstar/quiz/domain/QuizTest.kt
Labels: 🚀 BE, ✨ Feature

#37 feat: 게임방 리스트 조회 API 구현
  src/main/kotlin/yjh/cstar/room/application/RoomService.kt
  src/main/kotlin/yjh/cstar/room/application/port/RoomRepository.kt
  src/main/kotlin/yjh/cstar/room/infrastructure/RoomRepositoryAdapter.kt
  src/main/kotlin/yjh/cstar/room/presentation/RoomController.kt
  src/test/kotlin/yjh/cstar/room/application/RoomServiceTest.kt
Labels: 🚀 BE, ✨ Feature

#42 fix: 토큰 subject 생성 버그 수정
  src/main/kotlin/yjh/cstar/auth/jwt/TokenProvider.kt
Labels: 🔥 Bug, 🚀 BE

#43 fix: 게임엔진서비스버그수정
  src/main/kotlin/yjh/cstar/game/application/GameEngineService.kt
  src/main/kotlin/yjh/cstar/game/infrastructure/QueueRepositoryAdapter.kt
Labels: 🔥 Bug, 🚀 BE

#45 fix: 로그인 시 존재하지 않는 사용자에 대한 에러 코드 수정
  src/main/kotlin/yjh/cstar/auth/application/UserDetailService.kt
Labels: 🔥 Bug

#47 fix: 하드코딩된 playerId를 Authentication에서 가져오도록 수정
  src/main/kotlin/yjh/cstar/websocket/presentation/StompController.kt
Labels: 🔥 Bug

#49 refactor: 불필요한 코드 제거
  src/main/kotlin/yjh/cstar/auth/jwt/TokenProvider.kt
  src/main/kotlin/yjh/cstar/game/domain/GameResult.kt
Labels: 🛠 Refactor

#51 refactor: 인증 API 적용
  src/main/kotlin/yjh/cstar/config/SecurityConfig.kt
  src/main/kotlin/yjh/cstar/room/presentation/RoomController.kt
  src/main/kotlin/yjh/cstar/room/presentation/request/RoomJoinRequest.kt
  src/test/kotlin/yjh/cstar/room/concurrency/RoomConcurrencyTest.kt
Labels: 🚀 BE, ✨ Feature, 🛠 Refactor

#53 feat: 웹소켓 메세지 응답 양식 구현
  .gitignore
  src/main/kotlin/yjh/cstar/game/application/BroadCastService.kt
  src/main/kotlin/yjh/cstar/game/application/GameEngineService.kt
  src/main/kotlin/yjh/cstar/game/presentation/response/GameMessage.kt
Labels: 🚀 BE, ✨ Feature
