Repository FreakPeople/freak-CStar-backend, pull requests merged in 2025-04, with the labels that each got.

#142 feat: 모니터링 기능 추가
  cstar-api/build.gradle.kts
  cstar-api/docker/app/Dockerfile
  cstar-api/src/main/kotlin/yjh/cstar/config/SecurityConfig.kt
  cstar-api/src/main/resources/application-local.yml
  docker/monitoring/docker-compose.yml
  docker/monitoring/prometheus/prometheus.yml
Labels: 🚀 BE, ✨ Feature

#144 fix: flyway v4 sql 문 수정
  cstar-api/src/main/resources/db/V4__alter_tables_for_descriptive_quiz_and_workbook.sql
Labels: 🔥 Bug

#146 fix: deploy 스크립트 수정
  .github/workflows/deploy.yml
Labels: 🔥 Bug, 🚀 BE
