Repository FreakPeople/freak-CStar-backend, pull requests merged in 2025-02, with the labels that each got.

#129 fix: roomJoinEntity jpa 연결 테스트 실패 문제 해결
  src/test/kotlin/yjh/cstar/room/concurrency/RoomConcurrencyTest.kt
Labels: 🔥 Bug, 🚀 BE

#131 refactor: 싱글톤으로 테스트컨테이너를 관리하도록 변경
  src/test/kotlin/yjh/cstar/IntegrationTest.kt
  src/test/kotlin/yjh/cstar/MySQLTestContainer.kt
  src/test/kotlin/yjh/cstar/RedisTestContainer.kt
  src/test/kotlin/yjh/cstar/chat/ChatTest.kt
  src/test/kotlin/yjh/cstar/chat/application/PlayerAnswerSendServiceTest.kt
  src/test/kotlin/yjh/cstar/game/application/GameResultServiceTest.kt
  src/test/kotlin/yjh/cstar/jpa/JpaTest.kt
  src/test/kotlin/yjh/cstar/member/application/MemberServiceTest.kt
  src/test/kotlin/yjh/cstar/member/concurrency/MemberConcurrencyTest.kt
  src/test/kotlin/yjh/cstar/quiz/application/QuizServiceTest.kt
  src/test/kotlin/yjh/cstar/redis/RedisConcurrencyTest.kt
  src/test/kotlin/yjh/cstar/redis/RedisTest.kt
  src/test/kotlin/yjh/cstar/room/application/RoomServiceTest.kt
  src/test/kotlin/yjh/cstar/room/concurrency/RoomConcurrencyTest.kt
  src/test/resources/application-integration-test.yml
Labels: 🚀 BE, 🛠 Refactor, 💯 Test

#135 chore: CD 스크립트 변경
  .github/workflows/deploy.yml
  cstar-common/src/main/kotlin/yjh/cstar/common/exception/BaseErrorCode.kt
  cstar-common/src/main/kotlin/yjh/cstar/common/exception/BaseException.kt
Labels: 🔥 Bug, 🚀 BE

#136 chore: Dockerfile copy 경로 재설정
  cstar-api/docker/Dockerfile
Labels: 🔥 Bug, 🚀 BE

#137 chore: CD 스크립트에서 테스트 제외하고 빌드하도록 수정
  .github/workflows/deploy.yml
Labels: 🚀 BE
